<a href="https://colab.research.google.com/github/yulissajimenez-10/file_curso_NUMPY/blob/main/Creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#en python
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# en numpy 

np.arange(0,20) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(0,20,2) 

# primer valor inicio
# segundo valos stop
# tercer valos step 


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.zeros((10,5))
#crea una matriz con los valores en cero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,10)
# primer valo inicio
# segundo valor stop
# tercer valor cantidad de valores que quiero que se genere

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [15]:
np.eye(4)
#crea una matriz con la diagonal principal en 1 y el resto en cero

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(4)
# genera un arreglo con valores aleatorios

array([0.15731726, 0.09419953, 0.02721273, 0.39890816])

In [18]:
np.random.rand(4,4)
# genera un arreglo con valores aleatorios

array([[0.92860649, 0.45503073, 0.43347197, 0.77268954],
       [0.27407576, 0.51997978, 0.0673911 , 0.75654984],
       [0.15465747, 0.11204926, 0.89164626, 0.87195946],
       [0.86776996, 0.79881815, 0.53247508, 0.04491749]])

In [20]:
np.random.randint(1,15)
#genera un numero aletario entre 1 al 15

5

In [22]:
np.random.randint(1,100,(10,10))
# en esto generamos una estructura de 10 * 10 con valores aleatorios enteros entre 1  al  100


array([[67, 95,  5, 90, 24, 44, 99, 38, 59, 11],
       [63, 27, 52, 58, 33, 44, 47, 98, 31, 30],
       [42, 89, 25, 37, 46, 23, 36,  1, 94, 53],
       [89, 53, 99, 19, 75, 59, 80, 69, 60, 70],
       [73, 86, 70, 85, 75, 21, 96, 71, 43, 89],
       [99, 41, 40,  5, 63, 93, 94, 61,  8, 64],
       [60, 71, 61, 86, 98, 66, 53, 27, 31, 89],
       [26, 20, 94, 97, 23, 66, 70,  1, 29, 69],
       [74, 57, 66, 94, 63, 33, 97, 59, 87, 86],
       [ 2, 76, 56, 62, 95, 83, 70, 60, 80, 48]])