<a href="https://colab.research.google.com/github/yulissajimenez-10/file_curso_NUMPY/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
#tipo de dimensiones


In [5]:
# ESCALAR : 
scalar = np.array(42)
print(scalar) 
scalar.ndim 

42


0

In [6]:
#  VECTOR :
vector = np.array([1, 2, 3])
print(vector) 
vector.ndim 


[1 2 3]


1

In [7]:
# MATRIZ : 
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [8]:
# TENSOR :
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

In [ ]:
# AGREGAR O ELIMINAR DIMENSIONES

In [9]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [10]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [11]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [ ]:
# RETOS


In [ ]:
# DEFINE UN TENSOR DE 5 DIMENSIONES

In [14]:
tensor = np.array([[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]],[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]],[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]],[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]]])
print(tensor)
tensor.ndim

[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]]

   [[13 13 15]
    [16 17 18]
    [19 20 21]
    [22 23 24]]]


  [[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]]

   [[13 13 15]
    [16 17 18]
    [19 20 21]
    [22 23 24]]]]



 [[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]]

   [[13 13 15]
    [16 17 18]
    [19 20 21]
    [22 23 24]]]


  [[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]]

   [[13 13 15]
    [16 17 18]
    [19 20 21]
    [22 23 24]]]]]


5

In [15]:
vector = np.array([1, 2, 3], ndmin = 5)
print(vector) 
vector.ndim 

[[[[[1 2 3]]]]]


5

In [ ]:
# LINK DE  WEB NUMPY https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html