<a href="https://colab.research.google.com/github/yulissajimenez-10/file_curso_NUMPY/blob/main/shape_y_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# shape : indica la forma del arreglo


In [6]:
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [7]:
arr

array([[7, 7],
       [9, 3],
       [1, 1]])

In [8]:
# reshape : transforma el arrego mientras se mantenga los elementos

In [9]:
arr.reshape(1,6)

array([[7, 7, 9, 3, 1, 1]])

In [10]:
arr.reshape(2,3)

array([[7, 7, 9],
       [3, 1, 1]])

In [11]:
np.reshape(arr,(1,6))

array([[7, 7, 9, 3, 1, 1]])

In [12]:
#Se puede hacer un reshape como lo haría C.
np.reshape(arr,(2,3), 'C')


array([[7, 7, 9],
       [3, 1, 1]])

In [13]:
#También se puede hacer reshape a como lo haría Fortran
np.reshape(arr,(2,3), 'F')


array([[7, 1, 3],
       [9, 7, 1]])

In [14]:
#Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.
np.reshape(arr,(2,3), 'A')

array([[7, 7, 9],
       [3, 1, 1]])

In [ ]:
#No puedes cambiar la "forma" a la "forma" original del array, si tienes un (3,3) no lo puedes pasar a (4,2). 
#No respeta los 9 elementos del array original