<a href="https://colab.research.google.com/github/yulissajimenez-10/file_curso_NUMPY/blob/main/tipos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr

array([1., 2., 3., 4.])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr = arr.astype(np.float64)

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)